defaults: &DEFAULTS
  item_status:
    1: "出售中"
    2: "已关闭"
  trade_status:
    1: "未发货"
    2: "已发货"
  sms_account:
    user: "username"
    password: "password"

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
